#!/usr/bin/env bash
# Claude Code Stop hook for the AI-memory vault.
#
# Idempotently writes a concrete "Auto Session Log" block (branch, commits made
# this session, and uncommitted changes) into the active session log, so the
# NEXT session has real carryover instead of an empty template. Runs on every
# Stop and rewrites a single block, so the log always reflects the latest state
# even if the session is later killed abruptly.
#
# No-ops unless the session was launched via claude-start (which exports
# AI_MEM_ACTIVE_SESSION_LOG).
set -euo pipefail

log="${AI_MEM_ACTIVE_SESSION_LOG:-}"
[ -n "$log" ] || exit 0
[ -f "$log" ] || exit 0

marker="## Auto Session Log"

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '(no git)')"
repo="$(git rev-parse --show-toplevel 2>/dev/null || true)"

start_sha=""
[ -f "${log%.md}.startsha" ] && start_sha="$(cat "${log%.md}.startsha" 2>/dev/null || true)"

commits=""
if [ -n "$start_sha" ]; then
    commits="$(git log --no-merges --format='- %h %s' "${start_sha}..HEAD" 2>/dev/null || true)"
fi
[ -n "$commits" ] || commits="- (no commits this session)"

changes="$(git status --short 2>/dev/null | sed 's/^/- /' || true)"
[ -n "$changes" ] || changes="- (working tree clean)"

stamp="$(date '+%Y-%m-%d %H:%M:%S')"

block="$(cat <<EOF
${marker}
_Auto-generated ${stamp}. Edit the Session Outcome section above for durable notes._

* **Repo:** ${repo:-?}
* **Branch:** ${branch}
* **Commits this session:**
${commits}
* **Uncommitted changes at last checkpoint:**
${changes}
EOF
)"

# Strip any previous auto block (from marker to EOF), then append the fresh one.
tmp="$(mktemp)"
awk -v m="$marker" 'index($0, m)==1 { exit } { print }' "$log" > "$tmp"
printf '%s\n\n%s\n' "$(cat "$tmp")" "$block" > "$log"
rm -f "$tmp"

# Regenerate the per-project digest: a small, guaranteed-inlined summary of the
# "Session Outcome" bullets, so the next launch's prompt has actually-seen
# content instead of just a path the agent might or might not read. Rewritten
# in full each Stop, same as the block above.
digest_file="$(dirname "$log")/.digest.md"
digest_cap=400

extract_field() {
    grep -m1 -E "^\* \*\*${1}:\*\*" "$log" | sed -E "s|^\* \*\*${1}:\*\*[[:space:]]*||"
}

cap_field() {
    local text="$1" len=${#1}
    if [ "$len" -gt "$digest_cap" ]; then
        printf '%s\xe2\x80\xa6 (truncated, %d chars total \xe2\x80\x94 see %s)' "${text:0:$digest_cap}" "$len" "$log"
    else
        printf '%s' "$text"
    fi
}

session_date="$(grep -m1 -E '^date:' "$log" | sed -E 's/^date:[[:space:]]*//')"
[ -n "$session_date" ] || session_date="${stamp%% *}"

if [ "$commits" = "- (no commits this session)" ]; then
    commit_count=0
else
    commit_count="$(printf '%s\n' "$commits" | grep -c '^- ')"
fi

summary_raw="$(extract_field 'High-Level Summary')"
decisions_raw="$(extract_field 'Important Decisions')"
blockers_raw="$(extract_field 'Constraints / Blockers')"
next_raw="$(extract_field 'Next Step')"

[ -n "$summary_raw" ] || printf -v summary_raw '\xe2\x80\x94'
[ -n "$decisions_raw" ] || printf -v decisions_raw '\xe2\x80\x94'
[ -n "$blockers_raw" ] || printf -v blockers_raw '\xe2\x80\x94'
[ -n "$next_raw" ] || printf -v next_raw '\xe2\x80\x94'

{
    printf '<!-- auto-generated by session-summary.sh \xe2\x80\x94 do not edit by hand -->\n'
    printf '**Last session:** %s \xc2\xb7 %s commits \xc2\xb7 branch %s\n\n' "$session_date" "$commit_count" "$branch"
    printf '* **Summary:** %s\n' "$(cap_field "$summary_raw")"
    printf '* **Decisions:** %s\n' "$(cap_field "$decisions_raw")"
    printf '* **Blockers:** %s\n' "$(cap_field "$blockers_raw")"
    printf '* **Next:** %s\n' "$(cap_field "$next_raw")"
} > "$digest_file"
